### ISSUE TITLE
not working - Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by millennIumAMbiguity** [puggsoy/GMS-Explorer#1]
data.win: Stoneshard
file: Extensions.cs
line: 83 : long magic = br.ReadInt64();

System.IO.EndOfStreamException: 'Unable to read beyond the end of the stream.'

**Comment by puggsoy** [comment]
Apologies for the late reply, I haven't taken a look at fixing these issues until now. Can you provide a stack trace?
