### ISSUE TITLE
Prebuilt binaries?

### ISSUE THREAD

**Issue by merasmus44** [puggsoy/GMS-Explorer#3]
Is there a place I can acquire the prebuilt binaries for this project? I currently do not have the ability to compile C#.

**Comment by puggsoy** [comment]
Sorry, currently the project is not in a state where I'm happy to produce a public build. You can use GMExtract to extract content though: https://github.com/puggsoy/GMExtract

**Comment by merasmus44** [comment]
I have tried GMExtract, but the games I want to look at have too big a file size? (it says max_array_size reached)

**Comment by puggsoy** [comment]
Hmm OK, I might be happy to make a pre-release build if it would help. How big is the data.win file?

**Comment by merasmus44** [comment]
it's pretty big (91,000 KB). I also tried it on an 18,000KB file and it didn't work either.

**Comment by puggsoy** [comment]
I've made a pre-release binary now, feel free to give it a try.
