### ISSUE TITLE
Crashes with "Invalid PNG header" exception (also, doesn't support audio)

### ISSUE THREAD

**Issue by Synetech** [puggsoy/GMS-Explorer#5]
I'm trying to extract the background music from a game to listen to while I work, but nothing seems to work for this game (which was made with Gamemaker 2).

GMS-Explorer crashes with the exception "Invalid PNG header":

![Invalid PNG header exception](https://github.com/puggsoy/GMS-Explorer/assets/5210197/80708910-2ed4-42bc-8676-763bdbba1593)

(It looks like GMS-Explorer doesn't support extracting audio at all… 🤔)

**Comment by Windrainfox** [comment]
I got the same exception ;A;

**Comment by puggsoy** [comment]
The incompatability with GMS2 is already reported in #4. And you are correct, audio is not supported yet, but is planned.
